added sustainability classifications to rules
jborgers/PMD-jPinpoint-rules pull request #313
Opened 2024-05-31 07:04 UTC by stokpop

First classification round, please check and verify.

This is for issue #306 

Find "performance" tags without sustainability tags: should it still be added?

Blocked threads issues (e.g. without timeout): cpu or memory?
Timeout issues: cpu or io?

Can sustainability tags also have multiple area's? e.g. cpu and memory, or even all three: cpu, memory, io?

2024-05-31 15:34 UTC, jborgers requested changes
heel wat werk

2024-05-31 15:34 UTC, jborgers commented on src/main/resources/category/java/remoting.xml
> +            <property name="tag" value="sustainability-low" type="String" description="for-sonar"/>
not sure about this, how does it impact sustainability?

2024-05-31 15:34 UTC, jborgers commented on src/main/resources/category/java/remoting.xml
> +            <property name="tag" value="sustainability-low" type="String" description="for-sonar"/>
dit is informational, sustainability impact is niet duidelijk, zou ik weghalen.

2024-05-31 15:34 UTC, jborgers commented on src/main/resources/category/java/remoting.xml
> +            <property name="tag" value="sustainability-medium" type="String" description="for-sonar"/>
not sure about medium

2024-05-31 15:34 UTC, jborgers commented on src/main/resources/category/java/remoting.xml
> +            <property name="tag" value="cpu" type="String" description="for-sonar"/>
not sure about medium
also memory

2024-05-31 15:34 UTC, jborgers commented on src/main/resources/category/java/spring.xml
> +            <property name="tag" value="sustainability-low" type="String" description="for-sonar"/>
maybe medium

2024-05-31 15:34 UTC, jborgers commented on src/main/resources/category/java/spring.xml
>              <property name="tag" value="performance" type="String" description="for-sonar"/>
maybe not performance

2024-05-31 15:34 UTC, jborgers commented on src/main/resources/category/java/spring.xml
>              <property name="tag" value="performance" type="String" description="for-sonar"/>
maybe not performance

2024-06-03 12:15 UTC, stokpop commented on src/main/resources/category/java/common.xml
> +            <property name="tag" value="" type="String" description="for-sonar"/>
put on medium... toString() can be heavy when called *many* times for nothing

2024-06-03 12:19 UTC, stokpop commented on src/main/resources/category/java/common.xml
> +            <property name="tag" value="cpu" type="String" description="for-sonar"/>
yes

2024-06-03 12:19 UTC, stokpop commented on src/main/resources/category/java/common.xml
> +            <property name="tag" value="memory" type="String" description="for-sonar"/>
yes

2024-06-03 12:38 UTC, stokpop commented on src/main/resources/category/java/concurrent.xml
>              <property name="tag" value="performance" type="String" description="for-sonar"/>
See other remark about timeouts for threads... it is a potential stability (and performance) issue...

2024-06-03 12:39 UTC, stokpop commented on src/main/resources/category/java/concurrent.xml
> +	        <property name="tag" value="unpredictable" type="String" description="for-sonar"/>
yes, or "stability"

2024-06-03 12:42 UTC, stokpop commented on src/main/resources/category/java/concurrent.xml
>              <property name="tag" value="performance" type="String" description="for-sonar"/>
"stability"?

2024-06-17 07:45 UTC, stokpop commented on src/main/resources/category/java/remoting.xml
> +            <property name="tag" value="cpu" type="String" description="for-sonar"/>
Memory added. Moved to high.

2024-06-17 07:46 UTC, stokpop commented on src/main/resources/category/java/spring.xml
>              <property name="tag" value="performance" type="String" description="for-sonar"/>
removed performance tag

2024-06-17 07:52 UTC, stokpop commented
@jborgers can we go through to non-closed conversations together?

2024-06-17 13:03 UTC, jborgers commented
Sure, Friday?

Op ma 17 jun 2024 om 09:54 schreef Peter Paul Bakker <
***@***.***>:

> @jborgers <https://github.com/jborgers> can we go through to non-closed
> conversations together?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jborgers/PMD-jPinpoint-rules/pull/313#issuecomment-2172548968>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF3TVW2WHGYG6ZHVFJGOVEDZH2ITLAVCNFSM6AAAAABISH2D2KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNZSGU2DQOJWHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-21 10:55 UTC, merged