readme update
jborgers/PMD-jPinpoint-rules pull request #453
Opened 2024-12-09 15:14 UTC by jborgers

2024-12-09 15:58 UTC, stokpop requested changes
I also see some docs about Kotlin and PMD-7.0.0-SNAPSHOT branch, I think that also needs updates.

2024-12-09 15:58 UTC, stokpop commented on README.md
> +- the PMD-Plugin in you development environment.
typo: in your

2024-12-09 15:58 UTC, stokpop commented on README.md
>  - Alternatively, download and add your local copy: *rulesets/java/jpinpoint-rules.xml*
can turn this into a link? As here:

[rulesets/java/jpinpoint-rules.xml](https://raw.githubusercontent.com/jborgers/PMD-jPinpoint-rules/refs/heads/pmd7/rulesets/java/jpinpoint-rules.xml)

```text
[rulesets/java/jpinpoint-rules.xml](https://raw.githubusercontent.com/jborgers/PMD-jPinpoint-rules/refs/heads/pmd7/rulesets/java/jpinpoint-rules.xml)
```

2024-12-09 15:58 UTC, stokpop commented on README.md
>  - You can now perform the code checks using [right-click] on a folder or a file and choose:
we can add some screenshots (later?)

2024-12-09 15:58 UTC, stokpop commented on README.md
>  - Alternatively, download and add your local copy: *rulesets/java/jpinpoint-rules.xml*
Add this link also at Eclipse section

2024-12-13 16:05 UTC, jborgers commented on README.md
>  - You can now perform the code checks using [right-click] on a folder or a file and choose:
good idea

2024-12-13 16:06 UTC, jborgers commented on README.md
>  - You can now perform the code checks using [right-click] on a folder or a file and choose:
good idea

2024-12-13 16:07 UTC, merged