New rule: AvoidUnclearHttpRouteSecurity #364
jborgers/PMD-jPinpoint-rules pull request #464
Opened 2024-12-24 21:27 UTC by jborgers

2025-01-06 12:09 UTC, stokpop requested changes
From the issue #364 I thought this was a security issue. But it actually is a configuration issue that impacts performance, I think the problem description makes this clear.

Makes me wonder if in test envs where http might be used instead of https, the config might differ. This is an issue when the test env is a performance test env, which should actually be prod like, so also https.

2025-01-06 12:09 UTC, stokpop commented on docs/JavaCodePerformance.md
> +the key does not match, and you don't configure anything. Then, the default number of connections (2) will be used which may cause requests to wait long for a connection to become available (without
better? "and you don't configure anything" -> "and the intended configuration will not be used"

2025-01-06 12:09 UTC, stokpop commented on docs/JavaCodePerformance.md
> +      HttpRoute httpRouteGood = new HttpRoute(httpHost, null, secure);
add "// good"?

2025-01-10 10:30 UTC, jborgers commented on docs/JavaCodePerformance.md
> +      boolean secure = true;
check

2025-01-10 10:30 UTC, jborgers commented on docs/JavaCodePerformance.md
> +the key does not match, and you don't configure anything. Then, the default number of connections (2) will be used which may cause requests to wait long for a connection to become available (without
check

2025-01-10 10:31 UTC, jborgers commented on docs/JavaCodePerformance.md
> +the key does not match, and you don't configure anything. Then, the default number of connections (2) will be used which may cause requests to wait long for a connection to become available (without
check

2025-01-10 10:31 UTC, jborgers commented on docs/JavaCodePerformance.md
> +      HttpRoute httpRouteGood = new HttpRoute(httpHost, null, secure);
check

2025-01-10 10:38 UTC, merged