New Rule: AvoidSideEffectsInStreams #461
jborgers/PMD-jPinpoint-rules pull request #466
Opened 2024-12-31 10:11 UTC by jborgers

2025-01-06 14:10 UTC, stokpop requested changes
Looks good. Coverage is limited to some simple collections related methods such as `put`. Maybe add some others, see comments.

2025-01-06 14:10 UTC, stokpop commented on docs/JavaCodeQuality.md
> +                .peek(endpoint -> array[0] = endpoint)           // bad
peek should be used for debugging only, so maybe good to add "bad" examples with map or filter with side effects too... now it seems peek is bad (which it is) e.g. (based on example in the nice Goetz article): 

```java
.map(endpoint -> { array[0] = endpoint; endpoint })
```
-> good point

2025-01-10 16:48 UTC, jborgers commented on docs/JavaCodeQuality.md
> +                .peek(endpoint -> array[0] = endpoint)           // bad
I think that could be a good improvement to the rule, a next version

2025-01-10 17:52 UTC, jborgers commented on src/main/resources/category/java/common_std.xml
> +[ArgumentList[.//(MethodCall|MethodReference)[@MethodName=('set','add','put')]/VariableAccess or .//AssignmentExpression/ArrayAccess/*[1][pmd-java:nodeIs('VariableAccess')]
Covered all of those. 

To think about, all access is not appropriate according to Goetz, not just modifying. 
Maybe extend the rule? another rule? Many occurrences?

2025-01-10 17:52 UTC, merged